# Jekyll site
# Package your Jekyll site using the jekyll/builder Docker container image.
# Add steps that build, test, save build artifacts, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseRubyVersion@0
  inputs:
    versionSpec: '>= 2.6'
- script: |
    gem install jekyll bundler
    bundle install --retry=3 --jobs=4
  displayName: 'bundle install'
- script: |
    bundle install
    jekyll build
  displayName: 'jekyll'
- script: sudo npm install -g netlify-cli@2.0
  displayName: 'Install Netlify CLI'
- script: ls -als
  displayName: Stuff
- task: deploy@1
  inputs:
    authToken: '$(NETLIFY_PAT)'
    siteId: '$(NETLIFY_SITE_ID)'
    sourceDirectory: '$(System.DefaultWorkingDirectory)'
    isValidationOnly: false